### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by bartoszek** [mitsuba-renderer/mitsuba#124]
I've got stuck on enabling mitsuba to build against `python:3.8`
For `python:3.7` I've just need to add `3.7` here:
https://github.com/mitsuba-renderer/mitsuba/blob/26355676fa45feb5acca3f42b023a055ad2bb7e3/data/scons/detect_python.py#L59-L61
But this doesn't work for `3.8` version. I have infinitesimal understanding of `scons`, perhaps someone already have a fix for that?

**Comment by bartoszek** [comment]
Found it:
https://github.com/mitsuba-renderer/mitsuba/blob/26355676fa45feb5acca3f42b023a055ad2bb7e3/build/SConscript.configure#L33

**Comment by chx125ck** [comment]
Hi,
does your python binding work after you add '3.8' in both files?
