### ISSUE TITLE
Norm of shading normal is not 1.

### ISSUE THREAD

**Issue by hoshino042** [mitsuba-renderer/mitsuba#126]
When rendering a shading normal map, the norm of the normal vectors are not identical to 1, especially at the depth discontinuity. An example is shown below. 
![norm](https://user-images.githubusercontent.com/28819074/70320789-f2f48d00-1868-11ea-896a-8928e3a057b3.png)
The above image shows the norm of a rendered shading normal map of Stanford Armadillo. The right image shows a closeup view. The yellowish pixels have a norm very close to 1 (0.999, 0.998, etc.) while blueish pixels less than 1 (~0.7). It can be realized that the norm of the normal vectors at depth discontinuity are almost all less than 1.
Key settings regarding the rendering are as follows:
- Orthographic camera
- shNormal
- Halton sampler w/ 1024 sampleCount
- numpy mfilm w/ 32 digits

My questions are:
1. What happened when computing the shading normal vector for a pixel locating close to depth discontinuity?  
2. Are the directions of these non-unit-length normal vectors reliable? If so, then simply normalizing them solve the problem; Otherwise, we have to discard them.

**Comment by chaosink** [comment]
1. The `shNormal` results are just average of shading normals of all first hit samples in a pixel. The average of two unit normals may not be unit, for example, (1, 0, 0) and (-1, 0, 0).
2. Don't know how to process these non-unit normals properly.
