### ISSUE TITLE
error configuring on PopOS!

### ISSUE THREAD

**Issue by crazyrobinhood** [mitsuba-renderer/mitsuba#137]
Hi there. i was trying to compile on popOS 20.10 with 5.8.0-7630-generic kernel and I had this issue when launching cmake -Gninja ..

(I was following the compling guide)
thanks in advance

-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3.8 (found version "3.8.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
CMake Error at CMakeLists.txt:47 (message):
  Could not run resources/configure.py script: Traceback (most recent call
  last):

    File "/home/nk/mitsuba2/resources/configure.py", line 134, in <module>
      configurations = json.loads(s)
    File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
      obj, end = self.scan_once(s, idx)

  json.decoder.JSONDecodeError: Expecting ',' delimiter: line 75 column 9
  (char 425)

-- Configuring incomplete, errors occurred!

**Comment by merlinND** [comment]
Hi @crazyrobinhood,

I think maybe this is a [Mitsuba 2](https://github.com/mitsuba-renderer/mitsuba2)-related issue?
Could you please re-open the issue there and also include the contents of your `mitsuba.conf` file? (most likely there's a small typo in there like a missing `,`).
