### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by kongdai123** [mitsuba-renderer/mitsuba#139]
Hi!

I am trying to install Mitsuba 0.5.0 on a Ubuntu 18.04 machine with Python3.6 bindings, I am able to successfully build the code and I can run mitsuba and render images from the command line. I also checked that the python bindings library file is built at /dist/python/3.6/mitsuba.so.

However, when I try to import mitsuba in my python environment
```
  import sys
  sys.path.append("./mitsuba/dist/python")
  sys.path.append("./mitsuba/dist/python/3.6")
  

  import mitsuba
```

I get the following error

`ImportError: dynamic module does not define module export function (PyInit_mitsuba)`

I'm very confused on what this error means. I checked that the python environment I am running is indeed python 3.6

I was wondering if you have any suggestions on what this might mean, and what I should do to debug this.

Thank you very much and have a nice day!

Best,
Tianfu

**Comment by YouthImagination** [comment]
I have same problem. I build mitsuba0.6 on Ubuntu 18.04 and compile successfully. But I got an error when I import mitsuba with python 2.7
`
ImportError: dynamic module does not define init function (initmitsuba)
`
Have you solve this problem?
