### ISSUE TITLE
How to debug mitsuba using single-threaded?

### ISSUE THREAD

**Issue by Superlee506** [mitsuba-renderer/mitsuba#147]
As describe above, I want to debug the codes using single thread, how to enable it?

**Comment by merlinND** [comment]
I believe that running `mitsuba` with the `-p1` flag should use a single thread.

https://github.com/mitsuba-renderer/mitsuba/blob/cfeb7766e7a1513492451f35dc65b86409655a7b/src/mitsuba/mitsuba.cpp#L61-L63
