### ISSUE TITLE
Why not stop when the BSDF sampling ray hit the luminaire in MIPathTracer

### ISSUE THREAD

**Issue by Superlee506** [mitsuba-renderer/mitsuba#149]
As described above,  Why not stop the process when the ray hit the luminaire? 
[Line263](https://github.com/mitsuba-renderer/mitsuba/blob/master/src/integrators/path/path.cpp#L263)

**Comment by merlinND** [comment]
Hi @Superlee506,

In a real life room, imagine a dim light panel being itself lit by a very bright light source or environment lighting. Surfaces can be emissive and still receive light from somewhere else.
