### ISSUE TITLE
MIPMap Cache is not deleted

### ISSUE THREAD

**Issue by foreachthing** [mitsuba-renderer/mitsuba#17]
When using Blender (v2.78 on Windows 7 Pro) and Mitsuba 0.5, the MIPMap cache file(s) is/are not deleted.

Blender Output: H:\Blender\Files\maze\
MIPMap cache: %app-data%\Local\Temp\tmp_qgvsqas.mip

This file, tmp_qgvsqas.mip, also remains after successful render.
If I render the same scene again, a new temp-filename is issued and the same file exists multiple times. And these files can be very, very big!

**Comment by wjakob** [comment]
Hi @foreachthing,

I don't think this is something that should be fixed in Mitsuba, but rather in the Blender plugin. (It should delete the temporary directory). The goal of the MIP map files is that they persist so that Mitsuba can reuse them on the next run.

Best,
Wenzel
