### ISSUE TITLE
environment map 

### ISSUE THREAD

**Issue by Gzhji** [mitsuba-renderer/mitsuba#170]
Hi community,

I am rendering object with env map, is that possible to scale or translate env map just like assuming it is a virtual sphere?

Thanks!
Guanzhou,

**Comment by njroussel** [comment]
Hi @Gzhji 

[The `envmap` plugin takes a `to_world` parameter](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_emitters.html#environment-emitter-envmap) which allows you to control scale and rotation. Although it is practically implemented as a virtual sphere, we do not expose the means to translate it.
