### ISSUE TITLE
translate env map in spherical sensor 

### ISSUE THREAD

**Issue by Gzhji** [mitsuba-renderer/mitsuba#171]
Dear community,

I was trying to render the indoor scene with accurate env map coordinates.

Ground Truth image:
![Screenshot from 2023-03-09 18-00-58](https://user-images.githubusercontent.com/70720549/224179746-41faee5d-7233-45b4-a0ac-012b7773d1e6.png)

Env map I captured and created.
![image](https://user-images.githubusercontent.com/70720549/224179916-0fb5f883-0532-4bb5-8e91-1ff27484131f.png)

I capture the env map right outside the room, so the coordinate of env map should be calibrated.  
Under "spherical" sensor, I realized I can rotate the env map, but cannot translate it. Does anyone know the issue?

![image](https://user-images.githubusercontent.com/70720549/224180773-c37b1ccd-3e35-441a-ac11-fe6fcb327230.png)
```

<scene version="0.6.0">
    <sensor type="spherical">
        <sampler type="ldsampler">
            <integer name="sampleCount" value="256"/>
        </sampler>
        <film type="hdrfilm">
            <string name="pixelFormat" value="rgba"/>
            <integer name="width" value="512"/>
            <integer name="height" value="256"/>
            <boolean name="banner" value="false"/>
        </film>
        <transform name="toWorld">
            <scale x="-1" y="-1"/>
            <rotate x="1" angle="-90"/>
            <translate x="0" y="0" z="0"/>
        </transform>
    </sensor>
    <integrator type="volpath">
        <integer name="maxDepth" value="8"/>
    </integrator>
    <shape type="obj">
        <string name="filename" value="../data/zind/scenes/floormesh/new/new+0F+basement+10141541/tex_floor.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="1"/>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="../data/zind/scenes/floormesh/new/new+0F+basement+10141541/tex_ceiling.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="mask">
            <boolean name="ensureEnergyConservation" value="false"/>
            <spectrum name="opacity" value="1"/>
            <bsdf type="diffuse">
                <boolean name="ensureEnergyConservation" value="false"/>
                <spectrum name="reflectance" value="0"/>
            </bsdf>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="obj_cache/new+0F+basement+10141541/3_dark_wall_mesh.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="1"/>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="obj_cache/new+0F+basement+10141541/3_bright_wall_mesh.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
            <translate x="0" y="0" z="0"/>
        </transform>
        <bsdf type="mask">
            <boolean name="ensureEnergyConservation" value="false"/>
            <bsdf type="diffuse">
                <boolean name="ensureEnergyConservation" value="false"/>
                <spectrum name="reflectance" value="0"/>
            </bsdf>
            <texture name="opacity" type="bitmap">
                <string name="filename" value="obj_cache/new+0F+basement+10141541/3_bright_wall_tex_mask.png"/>
            </texture>
        </bsdf>
    </shape>
    <emitter type="envmap">
        <string name="filename" value="../data/zind/scenes/env_map/new/new+0F+basement+10141541.exr"/>
        <transform name="toWorld">
            <scale x="-1" y="-1"/>
            <rotate angle="-90" x="1"/>
            <rotate angle="-90" z="1"/>
            <translate x="0" y="5" z="0"/>
        </transform>
    </emitter>
</scene>
```

**Comment by Gzhji** [comment]
<scene version="0.6.0">
    <sensor type="spherical">
        <sampler type="ldsampler">
            <integer name="sampleCount" value="256"/>
        </sampler>
        <film type="hdrfilm">
            <string name="pixelFormat" value="rgba"/>
            <integer name="width" value="512"/>
            <integer name="height" value="256"/>
            <boolean name="banner" value="false"/>
        </film>
        <transform name="toWorld">
            <scale x="-1" y="-1"/>
            <rotate x="1" angle="-90"/>
            <translate x="0" y="0" z="0"/>
        </transform>
    </sensor>
    <integrator type="volpath">
        <integer name="maxDepth" value="8"/>
    </integrator>
    <shape type="obj">
        <string name="filename" value="../data/zind/scenes/floormesh/new/new+0F+basement+10141541/tex_floor.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="1"/>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="../data/zind/scenes/floormesh/new/new+0F+basement+10141541/tex_ceiling.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="mask">
            <boolean name="ensureEnergyConservation" value="false"/>
            <spectrum name="opacity" value="1"/>
            <bsdf type="diffuse">
                <boolean name="ensureEnergyConservation" value="false"/>
                <spectrum name="reflectance" value="0"/>
            </bsdf>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="obj_cache/new+0F+basement+10141541/3_dark_wall_mesh.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="1"/>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="obj_cache/new+0F+basement+10141541/3_bright_wall_mesh.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
            <translate x="0" y="0" z="0"/>
        </transform>
        <bsdf type="mask">
            <boolean name="ensureEnergyConservation" value="false"/>
            <bsdf type="diffuse">
                <boolean name="ensureEnergyConservation" value="false"/>
                <spectrum name="reflectance" value="0"/>
            </bsdf>
            <texture name="opacity" type="bitmap">
                <string name="filename" value="obj_cache/new+0F+basement+10141541/3_bright_wall_tex_mask.png"/>
            </texture>
        </bsdf>
    </shape>
    <emitter type="envmap">
        <string name="filename" value="../data/zind/scenes/env_map/new/new+0F+basement+10141541.exr"/>
        <transform name="toWorld">
            <scale x="-1" y="-1"/>
            <rotate angle="-90" x="1"/>
            <rotate angle="-90" z="1"/>
            <translate x="0" y="5" z="0"/>
        </transform>
    </emitter>
</scene>

**Comment by Gzhji** [comment]
<scene version="0.6.0">
    <sensor type="spherical">
        <sampler type="ldsampler">
            <integer name="sampleCount" value="256"/>
        </sampler>
        <film type="hdrfilm">
            <string name="pixelFormat" value="rgba"/>
            <integer name="width" value="512"/>
            <integer name="height" value="256"/>
            <boolean name="banner" value="false"/>
        </film>
        <transform name="toWorld">
            <scale x="-1" y="-1"/>
            <rotate x="1" angle="-90"/>
            <translate x="0" y="0" z="0"/>
        </transform>
    </sensor>
    <integrator type="volpath">
        <integer name="maxDepth" value="8"/>
    </integrator>
    <shape type="obj">
        <string name="filename" value="../data/zind/scenes/floormesh/new/new+0F+basement+10141541/tex_floor.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="1"/>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="../data/zind/scenes/floormesh/new/new+0F+basement+10141541/tex_ceiling.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="mask">
            <boolean name="ensureEnergyConservation" value="false"/>
            <spectrum name="opacity" value="1"/>
            <bsdf type="diffuse">
                <boolean name="ensureEnergyConservation" value="false"/>
                <spectrum name="reflectance" value="0"/>
            </bsdf>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="obj_cache/new+0F+basement+10141541/3_dark_wall_mesh.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
        </transform>
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="1"/>
        </bsdf>
    </shape>
    <shape type="obj">
        <string name="filename" value="obj_cache/new+0F+basement+10141541/3_bright_wall_mesh.obj"/>
        <transform name="toWorld">
            <translate x="0" y="0" z="-1.6"/>
            <rotate z="1" angle="180"/>
            <translate x="0" y="0" z="0"/>
        </transform>
        <bsdf type="mask">
            <boolean name="ensureEnergyConservation" value="false"/>
            <bsdf type="diffuse">
                <boolean name="ensureEnergyConservation" value="false"/>
                <spectrum name="reflectance" value="0"/>
            </bsdf>
            <texture name="opacity" type="bitmap">
                <string name="filename" value="obj_cache/new+0F+basement+10141541/3_bright_wall_tex_mask.png"/>
            </texture>
        </bsdf>
    </shape>
    <emitter type="envmap">
        <string name="filename" value="../data/zind/scenes/env_map/new/new+0F+basement+10141541.exr"/>
        <transform name="toWorld">
            <scale x="-1" y="-1"/>
            <rotate angle="-90" x="1"/>
            <rotate angle="-90" z="1"/>
            <translate x="0" y="5" z="0"/>
        </transform>
    </emitter>
</scene>

**Comment by chaosink** [comment]
The `toWorld` transform of `envmap` is applied on the ray direction only.
That means the `translate` component of `toWorld` has no effect.

In your case, what about just moving your camera left for some distance, so that the outdoor view can be in the middle of the door?

**Comment by Gzhji** [comment]
> The `toWorld` transform of `envmap` is applied on the ray direction only. That means the `translate` component of `toWorld` has no effect.
> 
> In your case, what about just moving your camera left for some distance, so that the outdoor view can be in the middle of the door?

Thanks chaosink,
I think the solution will be: to construct a sphere object, set it as emitter (type:area), then attach texture to it.
In this case, the sphere geometry can be translated in different axis and work as light source.

**Comment by chaosink** [comment]
Mitsuba doesn't support textured area emitter.
You may implement that.

**Comment by merlinND** [comment]
Hi @Gzhji,

If that's an option for you, textured area light sources are supported in Mitsuba 3: https://github.com/mitsuba-renderer/mitsuba3/blob/c69356bc24e79435340b5dc58d16cb0c5248368e/src/emitters/area.cpp#L73
