### ISSUE TITLE
How to create a series of .xml by using mitsuba

### ISSUE THREAD

**Issue by piaoyicongrong** [mitsuba-renderer/mitsuba#180]
I've created an animation where a cuboid moves through an environment, and I want to generate an XML document for each snapshot, which means I might create numerous XML documents at once. Does anyone know how to achieve this?

**Comment by njroussel** [comment]
Hi @piaoyicongrong 

I don't know of any existing tools that can do this.

Once you have one XML description, writing a script that can ingest it and
modify the position of your object should be fairly trivial. The script would
write its output to a new XML file.
