### ISSUE TITLE
Depth Extraction 

### ISSUE THREAD

**Issue by phanax** [mitsuba-renderer/mitsuba#21]
Hi,

I'm exactly using the following xml file to extract depth images from the shapenet v2 object models. However, the output is not a depth image but always a black and white image with slightly smoothed edges.

Do you have any recommendations to resolve this issue?

Thanks.

`<?xml version="1.0" encoding="utf-8"?>

<scene version="0.5.0">
	
    <shape type="obj">
        <string name="filename" value="$model" />
    </shape>

    <emitter type="constant" />

    <integrator type="field">
		<string name="field" value="distance" />
		<spectrum name="undefined" value="0" />
	</integrator>

    <sensor type="perspective">
        <transform name="toWorld">
            <lookAt target="0,0,0" origin="$view" up="0,1,0"/>
        </transform>

        <sampler type="ldsampler">
            <integer name="sampleCount" value="16"/>
        </sampler>

        <film type="hdrfilm">
            <integer name="width" value="256"/>
            <integer name="height" value="256"/>
            <boolean name="banner" value="false"/>
	<boolean name="attachLog" value="false"/>
        </film>
    </sensor>
</scene>`

**Comment by OrganicIrradiation** [comment]
Check your near and far clipping planes, e.g. 
```
<float name="farClip" value="1000"/>
<float name="nearClip" value="0.1"/>
```
Also make sure that you have the object and camera positioned appropriately.

**Comment by phanax** [comment]
Thanks @OrganicIrradiation. Objects are located in a unit cubic centered at the origin of the coordinate system and camera is dynamically placed over a unique sphere with a radius of 2, centered at the origin. Clipping also didn't work out.

**Comment by liweixue0215** [comment]
Hi, 
I can render the rgb image, but I can't render the correct depth map. I used the program in the example.
