### ISSUE TITLE
Unable to render any scene using the `hair` shape

### ISSUE THREAD

**Issue by amyspark** [mitsuba-renderer/mitsuba#25]
All hair-related rendering is not working as of 77d0885f8584547251a80cdc3d225282593917ae. 
I've tried Benedikt Bitterli's Fur Ball, Hair Curls and Straight Hair scenes. In all of them the console spams (snippet below):
```
2017-09-11 08:39:09 WARN  wrk2 [ImageBlock] Invalid sample value : [nan, nan, nan, 1, 1]
2017-09-11 08:39:09 WARN  wrk1 [ImageBlock] Invalid sample value : [nan, nan, nan, 1, 1]
2017-09-11 08:39:09 WARN  wrk2 [vector.h:538] Vector3: Division by zero!
2017-09-11 08:39:09 WARN  wrk0 [vector.h:538] Vector3: Division by zero!
2017-09-11 08:39:09 WARN  wrk3 [vector.h:538] Vector3: Division by zero!
2017-09-11 08:39:09 WARN  wrk0 [MIPMap] evalBilinear(): encountered a NaN!
2017-09-11 08:39:09 WARN  wrk3 [MIPMap] evalBilinear(): encountered a NaN!
2017-09-11 08:39:09 WARN  wrk3 [EnvironmentMap] pdfDirect(): encountered a NaN!
2017-09-11 08:39:09 WARN  wrk1 [vector.h:538] Vector3: Division by zero!
2017-09-11 08:39:09 WARN  wrk0 [EnvironmentMap] pdfDirect(): encountered a NaN!
```
and ends up with pitch black hair being rendered. The Curly Hair scene instantly crashes.

This happens in MacOS Sierra 10.12.6 as well as Windows 7 (MSVC 2017).

**Comment by wjakob** [comment]
Dear @amyspark,

we're currently 100% occupied with other research projects. It would be helpful if you could look into this yourself and post a PR to address the underlying issue.

Best,
Wenzel

**Comment by amyspark** [comment]
I'm no expert, but I'll do my best.
I started by intercepting the division by zeros, which in my case were caused by the integrator attempting to calculate the incident light here:
https://github.com/mitsuba-renderer/mitsuba/blob/933a05740f3656fbe8eb11e0a3b2014eb2e4d3a0/src/librender/integrator.cpp#L183
When Mitsuba intersects the sampled ray with the hair, this query https://github.com/mitsuba-renderer/mitsuba/blob/933a05740f3656fbe8eb11e0a3b2014eb2e4d3a0/src/librender/integrator.cpp#L150 generates an `Intersection` with the shading frame and UV partial position all set to zero. This is the same with any bsdf, and when it tries normalising that vector, it all fails.

**Comment by amyspark** [comment]
I tried `git bisect`ing since 1ca04133d98184369ca3383d3c399e1b393f8ae2 (when you bumped Mitsuba to 0.5.0). I couldn't get Mitsuba to compile there (lots of Boost uncaught exceptions, clang complaining about `libstdc++`, et al) so I resorted to manually looking backwards starting from the latest commit.

Counting from today, the first working commit I could find is b8480a3d6087afdad8cd25b970c9a8d33339600a.  The first bad one I could find is 8365668205ae20a889e6aab21470107604c8ba08.
`git bisect`ing them tells me the bug was introduced by ce80ddcb6d3fe0a7240f7230d9d148d776292f57, which is consistent with the shading frame issue I had observed.

**Comment by amyspark** [comment]
I've finally found the cause of the bug. It seems that previously, `Hair`'s shading frame was initialized to the geometry frame *with no further changes*:
https://github.com/mitsuba-renderer/mitsuba/blob/0a49106ad17aa01f9465bce17451ac8d674474f1/src/shapes/hair.cpp#L848
Now, the shading frame calculation is standardized with the rest of the shapes. This *was not done anywhere*  previously:
https://github.com/mitsuba-renderer/mitsuba/blob/ce80ddcb6d3fe0a7240f7230d9d148d776292f57/include/mitsuba/render/skdtree.h#L424

A workaround would be to revert the `computeShadingFrame` line and restore the initialization in `hair.cpp`, but in this way I break the rest of the `Shape`s.
