### ISSUE TITLE
Extracting depth maps

### ISSUE THREAD

**Issue by phanax** [mitsuba-renderer/mitsuba#29]
Hi,

I'm using the xml script below to extract depth maps from the shapenet v2 object models. The problem is that depth information around the edges seem to be filtered somehow and the pixels are either blurred or crooked and do not represent the real values of the depth information wrt to the camera positions. Depth values start from zero for the background and grow smoothly around the edges. A snapshot is also attached below. Do you have any idea to resolve this issue?

`<?xml version="1.0" encoding="utf-8"?>

<scene version="0.5.0">
	
    <shape type="shapenet">
        <string name="filename" value="/home/Data/ShapeNetCore.v2/02871439/6422a1f1dae8fd231e23f97c3de97d74/models/model_normalized.obj" />
    </shape>

    <emitter type="constant" />

    <integrator type="field">
		<string name="field" value="distance" />
	</integrator>

    <sensor type="perspective">
        <transform name="toWorld">
            <lookAt target="0,0,0" origin="2,2,2" up="0,1,0"/>
        </transform>

        <sampler type="ldsampler">
            <integer name="sampleCount" value="1"/>
        </sampler>
        <float name="fov" value="45"/>

        <film type="hdrfilm">
            <string name="pixelFormat" value="luminance" /> 
            <boolean name="banner" value="false"/>
        </film>
    </sensor>
</scene>
`

![screenshot from 2017-09-18 01-24-29](https://user-images.githubusercontent.com/15720990/30525922-19884eb0-9c11-11e7-8099-b0472f70c551.png)

**Comment by wjakob** [comment]
1. You'll have to render with a single sample per pixel.
2. You will probably also want to modify a deterministic sampler (e.g. ``halton``) so that it returns a perfect grid patterns for the first two dimensions. Making these modifications is beyond what I can officially support here though, so I fear that you are on your own.

**Comment by fangchangma** [comment]
@ibcny Did you manage to solve the problem?
