### ISSUE TITLE
mtsgui crash on linux

### ISSUE THREAD

**Issue by amyspark** [mitsuba-renderer/mitsuba#35]
`mtsgui` crashes on Ubuntu 16.04 + KDE Neon with the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Internal error: call to ThreadLocalPrivate::get()  precedes the construction of thread-specific data structures!
Abortado
```

**Comment by amyspark** [comment]
I'm running `mtsgui` inside VirtualBox with 3D acceleration enabled. Disabling it works around the issue.

As for the crash, a bit of gdb tells me that it crashes when attempting to log an error here:
https://github.com/mitsuba-renderer/mitsuba/blob/6d7d66175ce4b1bcf7a726e46345d9f24cf7e40c/src/libhw/x11session.cpp#L34
but I cannot figure out yet why it wouldn't be able to access the thread's `Logger` instance.

**Comment by mshafiei** [comment]
Did you find any solution to this?
