### ISSUE TITLE
Scons script   error on print  instruction 

### ISSUE THREAD

**Issue by sukoi26** [mitsuba-renderer/mitsuba#46]
the file SConscript.configure
and SConscript.install

print nok missing  ( ) as

```
if not os.path.exists(configFile):
        print '\nA configuration file must be selected! Have a look at http://www.mitsuba-renderer.org/docs.html'
Exit(1)
```

**Comment by iscaswcm** [comment]
On MacOS High Sierra, I met the same error, I guess python on MacOs High Sierra change its grammar, so U just plus (), and it work well. @sukoi26

**Comment by merlinND** [comment]
I believe this error comes from using Scons version 3.0+ (recently released), whereas the build scripts were written for Scons 2. The most reliable way to fix this issue is to use a recent version of Scons 2 (with Python 2), which you can install with:

```
pip2 install --egg 'SCons==2.5.1' --user
```

**Comment by sukoi26** [comment]
Yes,  i'm on Linux DEBIAN,  i use scons v3.0 ,    @iscaswcm , i add ()  and now seems OK
but i have a compil error.
 
it will be better to downgrade on V2.0 to keep the same as repository.

python 3.6 supported ?

th +all

**Comment by merlinND** [comment]
> python 3.6 supported

If you are referring to the Python bindings, yes, I believe that [they are supported](https://github.com/mitsuba-renderer/mitsuba/blob/master/data/scons/detect_python.py#L60).

Regarding Scons, if you use Scons 2.x (as recommended), then it will only run via Python 2.

**Comment by sukoi26** [comment]
ok i close, i  downgrade to scons 2.5.1 and python 2.7
