### ISSUE TITLE
Compiling on Mac not detecting Qt

### ISSUE THREAD

**Issue by bobgeller401** [mitsuba-renderer/mitsuba#53]
I'm trying to compile Mitsuba on Mac OS X Sierra but it doesn't detect the Qt installation from dependancies and therefore doesn't install the GUI. Here's my config.py file:

> BUILDDIR       = '#build/release'
DISTDIR        = '#Mitsuba.app'
CXX            = 'clang++'
CC             = 'clang'
CCFLAGS        = ['-mmacosx-version-min=10.12', '-march=native', '-funsafe-math-optimizations', '-fno-math-errno', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk', '-O3', '-Wall', '-Wno-deprecated-declarations', '-g', '-DMTS_DEBUG', '-DSINGLE_PRECISION', '-DSPECTRUM_SAMPLES=3', '-DMTS_SSE', '-DMTS_HAS_COHERENT_RT', '-fvisibility=hidden', '-ftemplate-depth=512', '-stdlib=libc++']
LINKFLAGS      = ['-framework', 'OpenGL', '-framework', 'Cocoa', '-mmacosx-version-min=10.12', '-Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk', '-Wl,-headerpad,128', '-stdlib=libc++']
CXXFLAGS       = ['-std=c++11']
BASEINCLUDE    = ['#include', '#dependencies/include']
BASELIBDIR     = ['#dependencies/lib']
BASELIB        = ['m', 'pthread', 'Half']
OEXRINCLUDE    = ['#dependencies/include/OpenEXR']
OEXRLIB        = ['IlmImf', 'Imath', 'Iex', 'z']
PNGLIB         = ['png16']
PNGINCLUDE     = ['#dependencies/include/libpng']
JPEGLIB        = ['jpeg']
JPEGINCLUDE    = ['#dependencies/include/libjpeg']
XERCESLIB      = ['xerces-c']
GLLIB          = ['GLEWmx', 'objc']
GLFLAGS        = ['-DGLEW_MX']
BOOSTINCLUDE   = ['#dependencies']
BOOSTLIB       = ['boost_filesystem', 'boost_system', 'boost_thread']
PYTHON27INCLUDE= ['/System/Library/Frameworks/Python.framework/Versions/2.7/Headers']
PYTHON27LIBDIR = ['/System/Library/Frameworks/Python.framework/Versions/2.7/lib']
PYTHON27LIB    = ['boost_python27', 'boost_system']
PYTHON35INCLUDE= ['#dependencies/include/python3.5']
PYTHON35LIB    = ['boost_python36', 'boost_system']
PYTHON36INCLUDE= ['#dependencies/include/python3.4']
PYTHON36LIB    = ['boost_python36', 'boost_system']
COLLADAINCLUDE = ['/usr/local/include/collada-dom2.4', '/usr/local/include/collada-dom2.4/1.4']
COLLADALIBDIR  = ['/usr/local/Cellar/collada-dom/2.4.4/lib']
COLLADALIB     = ['collada-dom2.4-dp']
QTDIR          = '#dependencies'
FFTWLIB        = ['fftw3']
>

I keep getting the error when running Scons "Unable to detect a Qt installation -- not building the GUI!". I even tried a local installation on my computer but it still doesn't detect it.

**Comment by bobgeller401** [comment]
The

**Comment by bobgeller401** [comment]
I tried a local installation of Qt but it didn't have the libqcocoa.dylib file in the frameworks folder, so even when I copied it over to the folder. The Mitsuba app didn't build. Hopefully somebody can help me build Mitsuba.

**Comment by hyperknot** [comment]
Any solution for this one? I have the Qt in dependencies, and I also have `brew install qt`, yet it's still not being detected. Does anyone know what needs to be modified?

**Comment by merlinND** [comment]
Please see the steps in https://github.com/mitsuba-renderer/mitsuba/issues/33#issuecomment-403407881. Feel free to re-open with more details if the issue is not solved!
