### ISSUE TITLE
Could not load the Qt platform plugin "window" in ""

### ISSUE THREAD

**Issue by tuket** [mitsuba-renderer/mitsuba#64]
I just downloaded the Mitsuba repo and the dependencies for windows. I had difficulties compiling it but it finally does compile.
Now I'm getting the following crash on start up.

![image](https://user-images.githubusercontent.com/4165974/35476958-cfe93222-03b9-11e8-8609-cf0886490e25.png)

There is no `qwindows.dll` file in the dependencies directory could that be the issue? How can I fix it?

**Comment by merlinND** [comment]
Hello @tuket,
Please see #52 where this issue is discussed and a workaround is proposed.

**Comment by tuket** [comment]
Yes! Finally, it works!
Thank you!
