### ISSUE TITLE
Compile code with -fPIC 

### ISSUE THREAD

**Issue by sreenithy** [mitsuba-renderer/mitsuba#87]
I am trying to install Mitsuba on Ubuntu, and I keep getting this error.

`/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1067:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."

 #error "You must build your code with position independent code if Qt was bui....

scons: *** [build/release/mtsgui/aboutdlg.o] Error 1
scons: building terminated because of errors.
`
Kindly help

**Comment by sreenithy** [comment]
I figured out the mistake.
I edited the config.py to include '-fPIC' and '-std=c++11'.

CXXFLAGS       = ['-O3', '-Wall','-fPIC','-std=c++11',.....]

This sorted the installation problem

**Comment by fu123456** [comment]
Hi, I also meet the same problem. As you said, I modified my config file. But this problem does also occur. So can you help me solve this problem? Thx.

**Comment by fu123456** [comment]
@sreenithy Hi, can you help me?
