### ISSUE TITLE
Where does the pixel value be divided by the sum of reconstruction weights?

### ISSUE THREAD

**Issue by chaosink** [mitsuba-renderer/mitsuba#96]
Sorry to bother you for asking such a question...

I can't find the code though I have tried for a long time.

**Comment by merlinND** [comment]
Hello @chaosink,

Depending on your combination of storage & output formats, I would look in one of those places:

https://github.com/mitsuba-renderer/mitsuba/blob/450a2b8a258f09ec7e0824861e2306340ccbb3f4/src/libcore/fmtconv.cpp#L955-L1072

https://github.com/mitsuba-renderer/mitsuba/blob/450a2b8a258f09ec7e0824861e2306340ccbb3f4/src/libcore/bitmap.cpp#L1618-L1621

**Comment by chaosink** [comment]
Thank you so much! @merlinND
